### ISSUE TITLE
Not able to run the codegen command

### ISSUE THREAD

**Issue by Nohac** [7nohe/openapi-react-query-codegen#48]
Using the command provided in the readme gives me the following error:
```
$ npx --package @7nohe/openapi-react-query-codegen openapi-rq -i ./spec.yaml -c fetch

test/frontend/node_modules/commander/index.js:638
  var normalized = this.normalize(argv.slice(2));
                                       ^

TypeError: Cannot read properties of undefined (reading 'slice')
    at Command.parse (test/frontend/node_modules/commander/index.js:638:40)
    at Object.<anonymous> (test/frontend/node_modules/@7nohe/openapi-react-query-codegen/dist/src/cli.js:24:6)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12)
    at node:internal/main/run_main_module:28:49

Node.js v21.7.1
```

**Comment by seriouslag** [comment]
Can you provide a reproducible repo? I tested on node 20 and 21 and had no issues.

**Comment by Nohac** [comment]
I had the same issue using https://github.com/ferdikoomen/openapi-typescript-codegen directly. I looked at the issues and found that this repo is no longer maintained, so I switched to the suggested https://github.com/hey-api/openapi-ts which worked perfectly fine.
