### ISSUE TITLE
Queries not being generated. v1.0.6

### ISSUE THREAD

**Issue by Jakob-Espersen** [7nohe/openapi-react-query-codegen#65]
Hi
I just upgraded to 1.0.6 and i now get the following error when trying to generate:

```
/node_modules/@7nohe/openapi-react-query-codegen/dist/service.mjs:52
            throw new Error("Method block not found");
                  ^

Error: Method block not found
    at file:///Users/user/Repos/app/node_modules/@7nohe/openapi-react-query-codegen/dist/service.mjs:52:19
    at Array.map (<anonymous>)
    at getMethodsFromService (file:///Users/user/Repos/app/node_modules/@7nohe/openapi-react-query-codegen/dist/service.mjs:47:20)
    at file:///Users/user/Repos/app/node_modules/@7nohe/openapi-react-query-codegen/dist/service.mjs:14:22
    at Array.map (<anonymous>)
    at getServices (file:///Users/user/Repos/app/node_modules/@7nohe/openapi-react-query-codegen/dist/service.mjs:11:26)
    at createSourceFile (file:///Users/user/Repos/app/node_modules/@7nohe/openapi-react-query-codegen/dist/createSource.mjs:17:27)
    at createSource (file:///Users/user/Repos/app/node_modules/@7nohe/openapi-react-query-codegen/dist/createSource.mjs:47:77)
    at generate (file:///Users/user/Repos/app/node_modules/@7nohe/openapi-react-query-codegen/dist/generate.mjs:37:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.11.0
```

terminal:  ``` npx openapi-rq  -o src/data/ -i <path_to_openapi_spec>```

the request directory is generated, but no queries.

**Comment by Jakob-Espersen** [comment]
Found out it was my typescript version that was below 5.3.3 :)
